package io.github.bohdankordon.vulcanschedulemonitor.vulcan.connection.secret;

import static org.assertj.core.api.Assertions.*;

import io.github.bohdankordon.vulcanschedulemonitor.vulcan.session.*;
import java.io.*;
import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.util.*;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

class SessionPayloadV2Test {
  private final SecretPayloadCodec codec = new SecretPayloadCodec();
  private static final String BASE = "https://secret-cookie-domain.invalid/SECRET_COOKIE_PATH/";

  @Test
  void v2PreservesAllFieldsAndNullableAttributesExactly() {
    var material =
        VulcanSessionMaterial.structured(
            URI.create(BASE),
            URI.create(BASE),
            "SUPER_SECRET_TOKEN",
            "SUPER_SECRET_APPGUID",
            List.of(
                new VulcanCookieMaterial(
                    "SUPER_SECRET_COOKIE_NAME",
                    "SUPER_SECRET_COOKIE_VALUE",
                    "/",
                    ".secret-cookie-domain.invalid",
                    true,
                    true),
                new VulcanCookieMaterial(
                    "SUPER_SECRET_COOKIE_NAME",
                    "other",
                    "/SECRET_COOKIE_PATH/",
                    "secret-cookie-domain.invalid",
                    false,
                    false),
                new VulcanCookieMaterial("unknown", "", null, null, false, false)));
    var bytes = codec.encodeSession(material);
    assertThat(java.nio.ByteBuffer.wrap(bytes).getInt()).isEqualTo(0x56534D32);
    var decoded = codec.decodeSession(bytes);
    assertThat(SessionFidelityDiagnostics.compare(material, decoded).allSame()).isTrue();
    assertThat(Arrays.equals(bytes, codec.encodeSession(decoded))).isTrue();
    assertThat(
            SessionFidelityDiagnostics.compare(
                    decoded, VulcanSession.fromMaterial(decoded).snapshotMaterial())
                .allSame())
        .isTrue();
    assertThatThrownBy(decoded::legacyCookieHeader).hasMessage("Legacy cookie header unavailable");
  }

  @Test
  void everyTruncatedV2PrefixAndOversizedPayloadIsRejected() {
    var cookie =
        new VulcanCookieMaterial(
            "SUPER_SECRET_COOKIE_NAME",
            "SUPER_SECRET_COOKIE_VALUE",
            "/SECRET_COOKIE_PATH/",
            null,
            false,
            true);
    var material =
        VulcanSessionMaterial.structured(
            URI.create(BASE),
            URI.create(BASE),
            "SUPER_SECRET_TOKEN",
            "SUPER_SECRET_APPGUID",
            List.of(cookie));
    var bytes = codec.encodeSession(material);
    for (int length = 0; length < bytes.length; length++) {
      byte[] prefix = Arrays.copyOf(bytes, length);
      assertThatThrownBy(() -> codec.decodeSession(prefix))
          .hasMessage("Stored VULCAN secret could not be decrypted")
          .hasNoCause();
    }
    assertThatThrownBy(() -> codec.decodeSession(new byte[32 * 1024 * 1024 + 1]))
        .hasMessage("Stored VULCAN secret could not be decrypted")
        .hasNoCause();
  }

  @Test
  void fixedV1LayoutStillDecodesAndOnlyASnapshotUpgradesToV2() throws Exception {
    var bytes = new ByteArrayOutputStream();
    try (var out = new DataOutputStream(bytes)) {
      // Independent VSM1 fixture layout, not generated by the current codec.
      out.writeInt(0x56534D31);
      for (String field :
          List.of(
              BASE,
              BASE,
              "SUPER_SECRET_TOKEN",
              "SUPER_SECRET_APPGUID",
              "SUPER_SECRET_COOKIE_NAME=A; SUPER_SECRET_COOKIE_NAME=B")) field(out, field);
    }
    var legacy = codec.decodeSession(bytes.toByteArray());
    assertThat(legacy.cookieRepresentation())
        .isEqualTo(VulcanSessionMaterial.CookieRepresentation.LEGACY_HEADER);
    assertThat(legacy.cookieCount()).isEqualTo(2);
    assertThat(Arrays.equals(bytes.toByteArray(), codec.encodeSession(legacy))).isTrue();
    var upgraded = VulcanSession.fromMaterial(legacy).snapshotMaterial();
    assertThat(upgraded.cookieCount())
        .isEqualTo(1); // Already lost legacy identities cannot be recovered.
    assertThat(upgraded.cookieRepresentation())
        .isEqualTo(VulcanSessionMaterial.CookieRepresentation.STRUCTURED);
    assertThat(java.nio.ByteBuffer.wrap(codec.encodeSession(upgraded)).getInt())
        .isEqualTo(0x56534D32);
    assertThat(codec.decodeSession(codec.encodeSession(upgraded)).sameCookiesAs(upgraded)).isTrue();
  }

  @ParameterizedTest
  @ValueSource(
      strings = {
        "negative",
        "zero",
        "excessive",
        "truncated",
        "oversized",
        "boolean",
        "path",
        "domain",
        "trailing",
        "duplicate",
        "nullName",
        "nullValue",
        "badNull",
        "utf8",
        "magic"
      })
  void malformedV2FailsClosedWithoutPartialAcceptanceOrSecretMessages(String kind)
      throws Exception {
    var bytes = new ByteArrayOutputStream();
    try (var out = new DataOutputStream(bytes)) {
      out.writeInt(kind.equals("magic") ? 0 : 0x56534D32);
      for (String field : List.of(BASE, BASE, "SUPER_SECRET_TOKEN", "SUPER_SECRET_APPGUID"))
        field(out, field);
      out.writeInt(
          switch (kind) {
            case "negative" -> -1;
            case "zero" -> 0;
            case "excessive" -> 1001;
            case "duplicate" -> 2;
            default -> 1;
          });
      for (int i = 0; i < (kind.equals("duplicate") ? 2 : 1); i++) {
        if (kind.equals("oversized")) {
          out.writeInt(257);
          break;
        }
        if (kind.equals("utf8")) {
          out.writeInt(1);
          out.writeByte(0xff);
        } else if (kind.equals("nullName")) out.writeInt(-1);
        else field(out, "SUPER_SECRET_COOKIE_NAME");
        if (kind.equals("nullValue")) out.writeInt(-1);
        else field(out, "SUPER_SECRET_COOKIE_VALUE");
        if (kind.equals("badNull")) out.writeInt(-2);
        else field(out, kind.equals("path") ? "SECRET_COOKIE_PATH" : "/SECRET_COOKIE_PATH/");
        field(
            out,
            kind.equals("domain")
                ? "https://SECRET_COOKIE_DOMAIN"
                : "secret-cookie-domain.invalid");
        out.writeByte(kind.equals("boolean") ? 2 : 1);
        if (!kind.equals("truncated")) out.writeByte(0);
      }
      if (kind.equals("trailing")) out.writeByte(0);
    }
    assertThatThrownBy(() -> codec.decodeSession(bytes.toByteArray()))
        .isInstanceOf(SecretDecryptionException.class)
        .hasMessage("Stored VULCAN secret could not be decrypted")
        .hasNoCause();
  }

  private static void field(DataOutputStream out, String value) throws IOException {
    byte[] bytes = value.getBytes(StandardCharsets.UTF_8);
    out.writeInt(bytes.length);
    out.write(bytes);
  }
}
