CREATE TABLE tracking_scope (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journal_id BIGINT NOT NULL,
    week_start DATE NOT NULL,
    week_end DATE NOT NULL,
    baseline_established BOOLEAN NOT NULL DEFAULT FALSE,
    last_success_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_tracking_scope_journal_week UNIQUE (journal_id, week_start),
    CONSTRAINT ck_tracking_scope_week_range CHECK (week_end = week_start + 6),
    CONSTRAINT ck_tracking_scope_baseline_success
        CHECK (baseline_established = (last_success_at IS NOT NULL))
);

CREATE TABLE schedule_change_state (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_id BIGINT NOT NULL,
    change_key VARCHAR(64) NOT NULL,
    fingerprint VARCHAR(64) NOT NULL,
    change_type VARCHAR(64) NOT NULL,
    lesson_date DATE NOT NULL,
    lesson_period_id BIGINT NOT NULL,
    group_id BIGINT,
    subject_id BIGINT,
    first_seen_at TIMESTAMPTZ NOT NULL,
    last_seen_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_schedule_change_state_scope
        FOREIGN KEY (scope_id) REFERENCES tracking_scope (id) ON DELETE CASCADE,
    CONSTRAINT uq_schedule_change_state_scope_key UNIQUE (scope_id, change_key)
);

CREATE INDEX ix_schedule_change_state_scope ON schedule_change_state (scope_id);
CREATE INDEX ix_schedule_change_state_lesson_slot
    ON schedule_change_state (lesson_date, lesson_period_id);
