CREATE TABLE notification_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(32) NOT NULL,
    journal_id BIGINT NOT NULL,
    week_start DATE NOT NULL,
    week_end DATE NOT NULL,
    active_change_count INTEGER,
    change_key VARCHAR(64),
    change_type VARCHAR(64),
    lesson_date DATE,
    lesson_period_id BIGINT,
    group_id BIGINT,
    subject_id BIGINT,
    status VARCHAR(16) NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ NOT NULL,
    lease_until TIMESTAMPTZ,
    claim_token UUID,
    created_at TIMESTAMPTZ NOT NULL,
    delivered_at TIMESTAMPTZ,
    last_failure_category VARCHAR(16),
    CONSTRAINT ck_notification_outbox_event_type CHECK (
        event_type IN ('BASELINE_ESTABLISHED', 'CHANGE_NEW', 'CHANGE_UPDATED', 'CHANGE_RESOLVED')
    ),
    CONSTRAINT ck_notification_outbox_status CHECK (
        status IN ('PENDING', 'IN_FLIGHT', 'DELIVERED', 'DEAD')
    ),
    CONSTRAINT ck_notification_outbox_failure_category CHECK (
        last_failure_category IS NULL
        OR last_failure_category IN ('RETRYABLE', 'PERMANENT', 'UNEXPECTED')
    ),
    CONSTRAINT ck_notification_outbox_week_range CHECK (week_end = week_start + 6),
    CONSTRAINT ck_notification_outbox_attempt_count CHECK (attempt_count >= 0),
    CONSTRAINT ck_notification_outbox_baseline_count CHECK (
        active_change_count IS NULL OR active_change_count >= 0
    ),
    CONSTRAINT ck_notification_outbox_payload CHECK (
        (
            event_type = 'BASELINE_ESTABLISHED'
            AND active_change_count IS NOT NULL
            AND change_key IS NULL
            AND change_type IS NULL
            AND lesson_date IS NULL
            AND lesson_period_id IS NULL
            AND group_id IS NULL
            AND subject_id IS NULL
        )
        OR
        (
            event_type IN ('CHANGE_NEW', 'CHANGE_UPDATED', 'CHANGE_RESOLVED')
            AND active_change_count IS NULL
            AND change_key IS NOT NULL
            AND change_type IS NOT NULL
            AND lesson_date IS NOT NULL
            AND lesson_period_id IS NOT NULL
        )
    ),
    CONSTRAINT ck_notification_outbox_delivery_state CHECK (
        (
            status = 'PENDING'
            AND lease_until IS NULL
            AND claim_token IS NULL
            AND delivered_at IS NULL
        )
        OR
        (
            status = 'IN_FLIGHT'
            AND lease_until IS NOT NULL
            AND claim_token IS NOT NULL
            AND delivered_at IS NULL
        )
        OR
        (
            status = 'DELIVERED'
            AND lease_until IS NULL
            AND claim_token IS NULL
            AND delivered_at IS NOT NULL
        )
        OR
        (
            status = 'DEAD'
            AND lease_until IS NULL
            AND claim_token IS NULL
            AND delivered_at IS NULL
        )
    )
);

CREATE INDEX ix_notification_outbox_pending
    ON notification_outbox (next_attempt_at, id)
    WHERE status = 'PENDING';

CREATE INDEX ix_notification_outbox_stale_claim
    ON notification_outbox (lease_until, id)
    WHERE status = 'IN_FLIGHT';
