CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE telegram_identity (
    app_user_id BIGINT PRIMARY KEY,
    telegram_user_id BIGINT NOT NULL,
    private_chat_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_telegram_identity_app_user
        FOREIGN KEY (app_user_id) REFERENCES app_user (id),
    CONSTRAINT uq_telegram_identity_telegram_user UNIQUE (telegram_user_id),
    CONSTRAINT uq_telegram_identity_private_chat UNIQUE (private_chat_id)
);

CREATE TABLE monitoring_subscription (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_user_id BIGINT NOT NULL,
    journal_id BIGINT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_monitoring_subscription_app_user
        FOREIGN KEY (app_user_id) REFERENCES app_user (id),
    CONSTRAINT uq_monitoring_subscription_user_journal UNIQUE (app_user_id, journal_id)
);

CREATE INDEX ix_monitoring_subscription_enabled_journal
    ON monitoring_subscription (journal_id, app_user_id)
    WHERE enabled;

ALTER TABLE notification_outbox
    ADD COLUMN recipient_user_id BIGINT;

ALTER TABLE notification_outbox
    ADD CONSTRAINT fk_notification_outbox_recipient_user
        FOREIGN KEY (recipient_user_id) REFERENCES app_user (id);

ALTER TABLE notification_outbox
    DROP CONSTRAINT ck_notification_outbox_failure_category;

ALTER TABLE notification_outbox
    ADD CONSTRAINT ck_notification_outbox_failure_category CHECK (
        last_failure_category IS NULL
        OR last_failure_category IN (
            'RETRYABLE', 'PERMANENT', 'UNEXPECTED', 'EXHAUSTED', 'UNROUTABLE'
        )
    );

UPDATE notification_outbox
SET status = 'DEAD',
    lease_until = NULL,
    claim_token = NULL,
    delivered_at = NULL,
    last_failure_category = 'UNROUTABLE'
WHERE recipient_user_id IS NULL
  AND status IN ('PENDING', 'IN_FLIGHT');

ALTER TABLE notification_outbox
    ADD CONSTRAINT ck_notification_outbox_actionable_recipient CHECK (
        status NOT IN ('PENDING', 'IN_FLIGHT') OR recipient_user_id IS NOT NULL
    );
