CREATE TABLE vulcan_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_user_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    remember_credentials BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    authenticated_at TIMESTAMPTZ,
    CONSTRAINT fk_vulcan_account_app_user
        FOREIGN KEY (app_user_id) REFERENCES app_user (id),
    CONSTRAINT uq_vulcan_account_app_user UNIQUE (app_user_id),
    CONSTRAINT ck_vulcan_account_status CHECK (
        status IN ('CONNECTED', 'RECONNECT_REQUIRED', 'DISCONNECTED')
    )
);

CREATE TABLE vulcan_account_secret (
    account_id BIGINT PRIMARY KEY,
    key_version INTEGER NOT NULL,
    session_nonce BYTEA NOT NULL,
    session_ciphertext BYTEA NOT NULL,
    credential_nonce BYTEA,
    credential_ciphertext BYTEA,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_vulcan_account_secret_account
        FOREIGN KEY (account_id) REFERENCES vulcan_account (id) ON DELETE CASCADE,
    CONSTRAINT ck_vulcan_account_secret_key_version CHECK (key_version > 0),
    CONSTRAINT ck_vulcan_account_secret_credential_pair CHECK (
        (credential_nonce IS NULL) = (credential_ciphertext IS NULL)
    )
);

CREATE TABLE vulcan_connect_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_user_id BIGINT NOT NULL,
    token_hash BYTEA NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    failed_attempts INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_vulcan_connect_token_app_user
        FOREIGN KEY (app_user_id) REFERENCES app_user (id),
    CONSTRAINT uq_vulcan_connect_token_hash UNIQUE (token_hash),
    CONSTRAINT ck_vulcan_connect_token_attempts CHECK (failed_attempts >= 0),
    CONSTRAINT ck_vulcan_connect_token_expiry CHECK (expires_at > created_at)
);

CREATE INDEX ix_vulcan_connect_token_expiry
    ON vulcan_connect_token (expires_at)
    WHERE consumed_at IS NULL;

CREATE TABLE vulcan_class_catalog (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vulcan_account_id BIGINT NOT NULL,
    journal_id BIGINT NOT NULL,
    class_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    school_unit VARCHAR(255),
    grade INTEGER,
    school_year INTEGER NOT NULL,
    valid_from DATE,
    valid_to DATE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    synced_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_vulcan_class_catalog_account
        FOREIGN KEY (vulcan_account_id) REFERENCES vulcan_account (id) ON DELETE CASCADE,
    CONSTRAINT uq_vulcan_class_catalog_account_journal
        UNIQUE (vulcan_account_id, journal_id),
    CONSTRAINT ck_vulcan_class_catalog_ids CHECK (journal_id > 0 AND class_id > 0)
);

CREATE INDEX ix_vulcan_class_catalog_account_active
    ON vulcan_class_catalog (vulcan_account_id, active, name, journal_id);
